[package]
name = "cargo-dtc"
version = "1.7.0"
edition = "2021"
license = "GPL-2.0-or-later"

[[bin]]
bench = false
path = "src/dtc.rs"
name = "cargo-dtc"

[dependencies]

[build-dependencies]
cc = "1.0"
